apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: customer-service
